POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Elon Musk",
    "number": "111-1111222"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Yi Lan Mah"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "22222"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
}


